### ISSUE TITLE
ToRawEpoch method causes integer overflow for distant future dates

### ISSUE THREAD

**Issue by jeremypaskali** [dejanfajfar/epoch.net#2]
Certain `DateTime` dates given to `DateTimeExtensions.ToRawEpoch` cause integer overflow when converting the `TimeSpan.TotalSeconds` to an integer.

You'll experience this if you write a unit test with `new DateTime(2099, 7, 4, 0, 0, 0)`.  You'll get an output of -2147483648.  (The value of `TotalSeconds` is `4086806400`).

**Comment by dejanfajfar** [comment]
This is something that should not happen.

The integer type is limited but as it stands we should get an overflow exception if the projected date is to far into the future.

For version 2.0 we will extend the types available for export and then this issue should be dealt with.

**Comment by dejanfajfar** [comment]
I have _fixed_ this issue for now with an **EpochOverflow** Exception that will be thrown if the DateTime is to far into the future/past. But a more complete resolution of this issue will be done with version 2.0.

The new version 1.1.24 already contains the fix. Here the link [https://www.nuget.org/packages/Epoch.net/1.1.24](https://www.nuget.org/packages/Epoch.net/1.1.24)
