### ISSUE TITLE
Unintended namespace issues

### ISSUE THREAD

**Issue by jeremypaskali** [dejanfajfar/epoch.net#3]
When using epoch.net via nuget, the actual usage differs because the compiler gets confused as to the name `Epoch` being a namespace or a class.

At the top:
![image](https://user-images.githubusercontent.com/2309189/51628034-ef3a6f00-1f11-11e9-8a3e-8f0944c8c4b0.png)

![image](https://user-images.githubusercontent.com/2309189/51628002-d5009100-1f11-11e9-85f3-627ac4ac8ffa.png)

After fixing the compilation error:

![image](https://user-images.githubusercontent.com/2309189/51628017-dfbb2600-1f11-11e9-8015-f0a21fd17cbf.png)

The incantation of `Epoch.net.Epoch` is a little verbose due to this namespace and class name clash.

**Comment by dejanfajfar** [comment]
The name conflict was resolved with the rename of the Epoch class to ```EpochTime```
