### ISSUE TITLE
Support double

### ISSUE THREAD

**Issue by jeremypaskali** [dejanfajfar/epoch.net#4]
When working with the `DateTime` class and with JSON Web Tokens, the specification calls for the Unix Epoch to be a double.  It would ease use of this nuget package if the API support double for seconds.

**Comment by dejanfajfar** [comment]
This is a clear downside of this release. I was thinking of introducing a ```ExactEpoch``` or something like that to add support for microseconds. But I will add fractals to as input and output types where milliseconds can be transported

**Comment by dejanfajfar** [comment]
Added a ```LongEpochTime``` in version 3.0 which is based on a ```int64```. But will introduce additional ```double``` extension methods to allow better interoperability
